import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { BadgeDollarSign, Building2, Calculator, Download, FileDown, FileText, Plus, Receipt, Search, Trash2, Truck, Upload, Users, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/components/language-provider";
import { PageIntro } from "@/components/site-sections";

type Customer={id:string;name:string;company:string;phone:string;email:string;address:string;notes?:string;createdAt:string};
type Supplier={id:string;name:string;company:string;phone:string;email:string;notes?:string;createdAt:string};
type Line={id:string;description:string;qty:number;unitPrice:number};
type Quote={id:string;customerId:string;status:"draft"|"sent"|"accepted"|"rejected"|"expired";lines:Line[];discount:number;tax:number;createdAt:string;validUntil?:string;notes?:string};
type Invoice={id:string;customerId:string;status:"unpaid"|"partial"|"paid"|"overdue";lines:Line[];discount:number;tax:number;paid:number;createdAt:string;dueDate?:string;notes?:string};
type Cash={id:string;type:"income"|"expense";category:string;amount:number;currency:"EGP"|"USD";description:string;date:string};
type Task={id:string;title:string;customerId?:string;priority:"low"|"normal"|"high";status:"open"|"done";dueDate?:string;createdAt:string};
type Tab="overview"|"customers"|"suppliers"|"quotes"|"invoices"|"cash"|"tasks"|"reports";
type Store={customers:Customer[];suppliers:Supplier[];quotes:Quote[];invoices:Invoice[];cash:Cash[];tasks:Task[]};

const KEY="az-business-data";
const EMPTY:Store={customers:[],suppliers:[],quotes:[],invoices:[],cash:[],tasks:[]};
const uid=(p:string)=>p+"-"+Date.now().toString(36).toUpperCase()+"-"+Math.random().toString(36).slice(2,5).toUpperCase();
const calc=(lines:Line[],discount=0,tax=0)=>{const subtotal=lines.reduce((s,x)=>s+x.qty*x.unitPrice,0);const net=Math.max(0,subtotal-discount);return {subtotal,discount,tax,total:net+net*tax/100};};
const money=(n:number,c:"EGP"|"USD"="EGP")=>n.toLocaleString("en-US",{maximumFractionDigits:2})+" "+c;
const read=():Store=>{try{const x=JSON.parse(localStorage.getItem(KEY)||"{}");return {...EMPTY,...x,tasks:x.tasks||[]};}catch{return EMPTY;}};

export const Route=createFileRoute("/business")({head:()=>({meta:[{title:"Business Center | AZ Solution BNS"},{name:"robots",content:"noindex,nofollow"}]}),component:BusinessPage});

function BusinessPage(){
 const {language}=useLanguage();const ar=language==="ar";
 const [data,setData]=useState<Store>(EMPTY);const [tab,setTab]=useState<Tab>("overview");const [search,setSearch]=useState("");
 const [customer,setCustomer]=useState({name:"",company:"",phone:"",email:"",address:"",notes:""});const [supplier,setSupplier]=useState({name:"",company:"",phone:"",email:"",notes:""});
 const [customerId,setCustomerId]=useState("");const [lines,setLines]=useState<Line[]>([{id:"1",description:"",qty:1,unitPrice:0}]);const [discount,setDiscount]=useState(0);const [tax,setTax]=useState(0);const [validUntil,setValidUntil]=useState("");const [docNotes,setDocNotes]=useState("");
 const [cash,setCash]=useState({type:"income" as Cash["type"],category:"Sale",amount:"",currency:"EGP" as Cash["currency"],description:""});
 const [task,setTask]=useState({title:"",customerId:"",priority:"normal" as Task["priority"],dueDate:""});
 useEffect(()=>setData(read()),[]);
 const save=(next:Store)=>{setData(next);localStorage.setItem(KEY,JSON.stringify(next));};
 const customerName=(id:string)=>data.customers.find(x=>x.id===id)?.name||"—";
 const resetDoc=()=>{setLines([{id:"1",description:"",qty:1,unitPrice:0}]);setDiscount(0);setTax(0);setValidUntil("");setDocNotes("");};
 const addCustomer=()=>{if(!customer.name.trim()||!customer.phone.trim())return;save({...data,customers:[{id:uid("CUS"),...customer,createdAt:new Date().toISOString()},...data.customers]});setCustomer({name:"",company:"",phone:"",email:"",address:"",notes:""});};
 const addSupplier=()=>{if(!supplier.name.trim())return;save({...data,suppliers:[{id:uid("SUP"),...supplier,createdAt:new Date().toISOString()},...data.suppliers]});setSupplier({name:"",company:"",phone:"",email:"",notes:""});};
 const createQuote=()=>{const ls=lines.filter(x=>x.description.trim()&&x.qty>0);if(!customerId||!ls.length)return;save({...data,quotes:[{id:uid("QT"),customerId,status:"draft",lines:ls,discount,tax,createdAt:new Date().toISOString(),validUntil:validUntil||undefined,notes:docNotes||undefined},...data.quotes]});resetDoc();};
 const createInvoice=()=>{const ls=lines.filter(x=>x.description.trim()&&x.qty>0);if(!customerId||!ls.length)return;save({...data,invoices:[{id:uid("INV"),customerId,status:"unpaid",lines:ls,discount,tax,paid:0,createdAt:new Date().toISOString(),notes:docNotes||undefined},...data.invoices]});resetDoc();};
 const addCash=()=>{const n=Number(cash.amount);if(!n||n<=0)return;save({...data,cash:[{id:uid("TXN"),...cash,amount:n,date:new Date().toISOString()},...data.cash]});setCash({type:"income",category:"Sale",amount:"",currency:"EGP",description:""});};
 const addTask=()=>{if(!task.title.trim())return;save({...data,tasks:[{id:uid("TSK"),...task,status:"open",createdAt:new Date().toISOString()},...data.tasks]});setTask({title:"",customerId:"",priority:"normal",dueDate:""});};
 const updateQuote=(id:string,status:Quote["status"])=>save({...data,quotes:data.quotes.map(x=>x.id===id?{...x,status}:x)});
 const updateInvoice=(id:string,status:Invoice["status"],paid:number)=>save({...data,invoices:data.invoices.map(x=>x.id===id?{...x,status,paid:Math.max(0,paid)}:x)});
 const toggleTask=(id:string)=>save({...data,tasks:data.tasks.map(x=>x.id===id?{...x,status:x.status==="done"?"open":"done"}:x)});
 const deleteItem=(collection:keyof Store,id:string)=>save({...data,[collection]:(data[collection] as {id:string}[]).filter(x=>x.id!==id)} as Store);
 const stats=useMemo(()=>{const income=data.cash.filter(x=>x.type==="income"&&x.currency==="EGP").reduce((s,x)=>s+x.amount,0);const expense=data.cash.filter(x=>x.type==="expense"&&x.currency==="EGP").reduce((s,x)=>s+x.amount,0);const outstanding=data.invoices.reduce((s,x)=>s+Math.max(0,calc(x.lines,x.discount,x.tax).total-x.paid),0);const overdue=data.invoices.filter(x=>x.status==="overdue").length;const openTasks=data.tasks.filter(x=>x.status==="open").length;return{income,expense,profit:income-expense,outstanding,overdue,openTasks,quoted:data.quotes.reduce((s,x)=>s+calc(x.lines,x.discount,x.tax).total,0),invoiced:data.invoices.reduce((s,x)=>s+calc(x.lines,x.discount,x.tax).total,0)}},[data]);
 const filtered=data.customers.filter(x=>(x.name+" "+x.company+" "+x.phone+" "+x.email).toLowerCase().includes(search.toLowerCase()));
 const exportData=()=>{const blob=new Blob([JSON.stringify({version:2,exportedAt:new Date().toISOString(),data},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="az-solution-business-backup.json";a.click();URL.revokeObjectURL(a.href);};
 const importData=(file:File)=>{const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result));const next=parsed.data||parsed;if(next.customers&&next.quotes&&next.invoices&&next.cash){save({...EMPTY,...next,tasks:next.tasks||[]});}}catch{}};reader.readAsText(file);};
 const printDoc=(title:string,id:string,customerId:string,docLines:Line[],discountValue:number,taxValue:number)=>{const c=data.customers.find(x=>x.id===customerId);const totals=calc(docLines,discountValue,taxValue);const rows=docLines.map(x=>"<tr><td>"+x.description+"</td><td>"+x.qty+"</td><td>"+x.unitPrice+"</td><td>"+(x.qty*x.unitPrice)+"</td></tr>").join("");const html="<html><head><title>"+title+" "+id+"</title><style>body{font-family:Arial;padding:40px}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ddd;padding:10px;text-align:left}.total{font-size:22px;font-weight:bold}</style></head><body><h1>AZ Solution BNS</h1><h2>"+title+" — "+id+"</h2><p><b>Customer:</b> "+(c?.name||"—")+" "+(c?.company||"")+"</p><table><tr><th>Item</th><th>Qty</th><th>Unit Price</th><th>Total</th></tr>"+rows+"</table><p>Subtotal: "+totals.subtotal.toFixed(2)+"</p><p>Discount: "+totals.discount.toFixed(2)+"</p><p>Tax: "+totals.tax+"%</p><p class='total'>Total: "+totals.total.toFixed(2)+" EGP</p></body></html>";const w=window.open("","_blank","width=900,height=700");if(w){w.document.write(html);w.document.close();w.print();}};
 const convertQuote=(q:Quote)=>{const inv:Invoice={id:uid("INV"),customerId:q.customerId,status:"unpaid",lines:q.lines,discount:q.discount,tax:q.tax,paid:0,createdAt:new Date().toISOString(),notes:q.notes};save({...data,invoices:[inv,...data.invoices],quotes:data.quotes.map(x=>x.id===q.id?{...x,status:"accepted"}:x)});setTab("invoices");};
 const tabs:[Tab,string,string,any][]=[["overview","نظرة عامة","Overview",BadgeDollarSign],["customers","العملاء","Customers",Users],["suppliers","الموردون","Suppliers",Truck],["quotes","عروض الأسعار","Quotations",FileText],["invoices","الفواتير","Invoices",Receipt],["cash","الحسابات","Cashflow",WalletCards],["tasks","المهام","Tasks",Calculator],["reports","التقارير","Reports",Calculator]];
 return <><PageIntro icon={Building2} eyebrow={{ar:"نظام تشغيل الشركة",en:"Company Operating System"}} title={{ar:"AZ Solution Business OS",en:"AZ Solution Business OS"}} description={{ar:"CRM ومبيعات وعروض أسعار وفواتير وموردون وحسابات ومهام وتقارير في مركز واحد.",en:"CRM, sales, quotations, invoices, suppliers, cashflow, tasks and reporting in one center."}}/>
 <section className="bg-secondary py-8"><div className="container-shell">
 <div className="flex flex-wrap gap-2">{tabs.map(([id,a,e,I])=><button key={id} onClick={()=>setTab(id)} className={"inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm font-semibold "+(tab===id?"bg-primary text-primary-foreground":"bg-card hover:bg-accent")}><I className="h-4 w-4"/>{ar?a:e}</button>)}</div>
 {tab==="overview"&&<><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric t={ar?"الإيرادات":"Revenue"} v={money(stats.income)}/><Metric t={ar?"المصروفات":"Expenses"} v={money(stats.expense)}/><Metric t={ar?"صافي التشغيل":"Operating profit"} v={money(stats.profit)}/><Metric t={ar?"المستحق":"Outstanding"} v={money(stats.outstanding)}/><Metric t={ar?"قيمة العروض":"Quoted pipeline"} v={money(stats.quoted)}/><Metric t={ar?"الفواتير":"Invoiced"} v={money(stats.invoiced)}/><Metric t={ar?"المهام المفتوحة":"Open tasks"} v={String(stats.openTasks)}/><Metric t={ar?"الفواتير المتأخرة":"Overdue invoices"} v={String(stats.overdue)}/></div><div className="mt-6 flex flex-wrap gap-2"><Button variant="outline" onClick={exportData}><Download/>{ar?"نسخة احتياطية":"Backup"}</Button><label className="inline-flex cursor-pointer items-center gap-2 rounded-md border bg-background px-4 py-2 text-sm font-medium"><Upload/>{ar?"استعادة نسخة":"Restore"}<input type="file" accept=".json" className="hidden" onChange={e=>e.target.files?.[0]&&importData(e.target.files[0])}/></label></div></>}
 {tab==="customers"&&<Panel t={ar?"العملاء والشركات":"Customers & Companies"}><div className="grid gap-2 md:grid-cols-6">{(["name","company","phone","email","address","notes"] as const).map(k=><input key={k} value={customer[k]} onChange={e=>setCustomer({...customer,[k]:e.target.value})} placeholder={k==="name"?(ar?"اسم العميل":"Customer name"):k==="company"?(ar?"الشركة":"Company"):k} className="h-10 rounded-md border border-input bg-background px-3 text-sm"/>)}<Button onClick={addCustomer}><Plus/> {ar?"إضافة":"Add"}</Button></div><div className="mt-4 flex gap-2"><Search className="mt-3 h-4 w-4"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={ar?"بحث...":"Search..."} className="h-10 flex-1 rounded-md border px-3"/></div><div className="mt-4 grid gap-2">{filtered.map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-background p-4"><div><b>{x.name}</b><p className="text-xs text-muted-foreground">{x.company||"—"} · {x.phone} · {x.email||"—"}</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>{setCustomerId(x.id);setTab("quotes")}}><FileText/>{ar?"عرض سعر":"Quote"}</Button><Button variant="outline" onClick={()=>deleteItem("customers",x.id)}><Trash2/></Button></div></div>)}{!filtered.length&&<Empty t={ar?"لا يوجد عملاء":"No customers yet."}/>}</div></Panel>}
 {tab==="suppliers"&&<Panel t={ar?"الموردون":"Suppliers"}><div className="grid gap-2 md:grid-cols-6">{(["name","company","phone","email","notes"] as const).map(k=><input key={k} value={supplier[k]} onChange={e=>setSupplier({...supplier,[k]:e.target.value})} placeholder={k} className="h-10 rounded-md border px-3"/>) }<Button onClick={addSupplier}><Plus/>{ar?"إضافة":"Add"}</Button></div><div className="mt-4 grid gap-2">{data.suppliers.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl border bg-background p-4"><div><b>{x.name}</b><p className="text-xs text-muted-foreground">{x.company||"—"} · {x.phone||"—"} · {x.email||"—"}</p></div><Button variant="outline" onClick={()=>deleteItem("suppliers",x.id)}><Trash2/></Button></div>)}</div></Panel>}
 {tab==="quotes"&&<Panel t={ar?"عروض الأسعار":"Quotations"}><DocEditor ar={ar} customers={data.customers} customerId={customerId} setCustomerId={setCustomerId} lines={lines} setLines={setLines} discount={discount} setDiscount={setDiscount} tax={tax} setTax={setTax} validUntil={validUntil} setValidUntil={setValidUntil} notes={docNotes} setNotes={setDocNotes} add={createQuote} label={ar?"حفظ عرض السعر":"Save quotation"}/><div className="mt-6 space-y-2">{data.quotes.map(x=><Doc key={x.id} id={x.id} customer={customerName(x.customerId)} amount={calc(x.lines,x.discount,x.tax).total} status={x.status} ar={ar} onStatus={s=>updateQuote(x.id,s as Quote["status"])} print={()=>printDoc(ar?"عرض سعر":"Quotation",x.id,x.customerId,x.lines,x.discount,x.tax)} convert={()=>convertQuote(x)} canConvert={x.status!=="accepted"}/>)}</div></Panel>}
 {tab==="invoices"&&<Panel t={ar?"الفواتير والتحصيل":"Invoices & Collections"}><DocEditor ar={ar} customers={data.customers} customerId={customerId} setCustomerId={setCustomerId} lines={lines} setLines={setLines} discount={discount} setDiscount={setDiscount} tax={tax} setTax={setTax} validUntil="" setValidUntil={()=>{}} notes={docNotes} setNotes={setDocNotes} add={createInvoice} label={ar?"إنشاء فاتورة":"Create invoice"}/><div className="mt-6 space-y-2">{data.invoices.map(x=><div key={x.id} className="rounded-xl border bg-background p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><b>{x.id}</b><p className="text-sm">{customerName(x.customerId)} · {money(calc(x.lines,x.discount,x.tax).total)}</p><p className="text-xs text-muted-foreground">{ar?"المتبقي":"Remaining"}: {money(Math.max(0,calc(x.lines,x.discount,x.tax).total-x.paid))}</p></div><div className="flex flex-wrap gap-2"><select value={x.status} onChange={e=>updateInvoice(x.id,e.target.value as Invoice["status"],x.paid)} className="h-9 rounded-md border px-2 text-sm"><option value="unpaid">{ar?"غير مدفوع":"Unpaid"}</option><option value="partial">{ar?"جزئي":"Partial"}</option><option value="paid">{ar?"مدفوع":"Paid"}</option><option value="overdue">{ar?"متأخر":"Overdue"}</option></select><input type="number" value={x.paid} onChange={e=>updateInvoice(x.id,x.status,Number(e.target.value))} className="h-9 w-28 rounded-md border px-2 text-sm" placeholder="Paid"/><Button variant="outline" onClick={()=>printDoc(ar?"فاتورة":"Invoice",x.id,x.customerId,x.lines,x.discount,x.tax)}><FileDown/></Button><Button variant="outline" onClick={()=>deleteItem("invoices",x.id)}><Trash2/></Button></div></div></div>)}</div></Panel>}
 {tab==="cash"&&<Panel t={ar?"الإيرادات والمصروفات":"Income & Expenses"}><div className="grid gap-2 md:grid-cols-5"><select value={cash.type} onChange={e=>setCash({...cash,type:e.target.value as Cash["type"]})} className="h-10 rounded-md border px-3"><option value="income">{ar?"إيراد":"Income"}</option><option value="expense">{ar?"مصروف":"Expense"}</option></select><input value={cash.category} onChange={e=>setCash({...cash,category:e.target.value})} placeholder={ar?"التصنيف":"Category"} className="h-10 rounded-md border px-3"/><input type="number" value={cash.amount} onChange={e=>setCash({...cash,amount:e.target.value})} placeholder={ar?"القيمة":"Amount"} className="h-10 rounded-md border px-3"/><select value={cash.currency} onChange={e=>setCash({...cash,currency:e.target.value as Cash["currency"]})} className="h-10 rounded-md border px-3"><option>EGP</option><option>USD</option></select><Button onClick={addCash}><Plus/>{ar?"تسجيل":"Record"}</Button></div><input value={cash.description} onChange={e=>setCash({...cash,description:e.target.value})} placeholder={ar?"وصف العملية":"Description"} className="mt-2 h-10 w-full rounded-md border px-3"/><div className="mt-4 space-y-2">{data.cash.map(x=><div key={x.id} className="flex items-center justify-between rounded-xl border bg-background p-4"><span><b>{x.category}</b><p className="text-xs text-muted-foreground">{x.description}</p></span><div className="flex items-center gap-3"><b className={x.type==="expense"?"text-destructive":""}>{x.type==="expense"?"-":"+"}{money(x.amount,x.currency)}</b><Button variant="outline" onClick={()=>deleteItem("cash",x.id)}><Trash2/></Button></div></div>)}</div></Panel>}
 {tab==="tasks"&&<Panel t={ar?"المهام والمتابعة":"Tasks & Follow-up"}><div className="grid gap-2 md:grid-cols-5"><input value={task.title} onChange={e=>setTask({...task,title:e.target.value})} placeholder={ar?"المهمة":"Task"} className="h-10 rounded-md border px-3"/><select value={task.customerId} onChange={e=>setTask({...task,customerId:e.target.value})} className="h-10 rounded-md border px-3"><option value="">{ar?"عميل اختياري":"Optional customer"}</option>{data.customers.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={task.priority} onChange={e=>setTask({...task,priority:e.target.value as Task["priority"]})} className="h-10 rounded-md border px-3"><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option></select><input type="date" value={task.dueDate} onChange={e=>setTask({...task,dueDate:e.target.value})} className="h-10 rounded-md border px-3"/><Button onClick={addTask}><Plus/>{ar?"إضافة":"Add"}</Button></div><div className="mt-4 space-y-2">{data.tasks.map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-background p-4"><div className={x.status==="done"?"line-through opacity-60":""}><b>{x.title}</b><p className="text-xs text-muted-foreground">{x.customerId?customerName(x.customerId):""} {x.dueDate?" · "+x.dueDate:""} · {x.priority}</p></div><div className="flex gap-2"><Button variant="outline" onClick={()=>toggleTask(x.id)}>{x.status==="done"?(ar?"فتح":"Reopen"):(ar?"تم":"Done")}</Button><Button variant="outline" onClick={()=>deleteItem("tasks",x.id)}><Trash2/></Button></div></div>)}</div></Panel>}
 {tab==="reports"&&<Panel t={ar?"التقارير والإدارة":"Reports & Management"}><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4"><Metric t={ar?"الإيرادات":"Revenue"} v={money(stats.income)}/><Metric t={ar?"المصروفات":"Expenses"} v={money(stats.expense)}/><Metric t={ar?"صافي التشغيل":"Operating profit"} v={money(stats.profit)}/><Metric t={ar?"هامش التشغيل":"Operating margin"} v={stats.income?(stats.profit/stats.income*100).toFixed(1)+"%":"0%"}/></div><div className="mt-6 rounded-xl border p-4"><h3 className="font-bold">{ar?"نسخ البيانات":"Data portability"}</h3><p className="mt-1 text-sm text-muted-foreground">{ar?"استخدم النسخة الاحتياطية لنقل بيانات النظام بين الأجهزة قبل ربط قاعدة البيانات.":"Use JSON backup/restore to move data between devices before connecting a database."}</p><div className="mt-3"><Button variant="outline" onClick={exportData}><Download/>{ar?"تصدير كامل":"Export full backup"}</Button></div></div></Panel>}
 </div></section></>;
}

function Metric({t,v}:{t:string;v:string}){return <div className="stat-card"><p className="text-sm text-muted-foreground">{t}</p><p className="mt-2 text-2xl font-black">{v}</p></div>}
function Panel({t,children}:{t:string;children:ReactNode}){return <div className="mt-6 rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 className="text-xl font-black">{t}</h2>{children}</div>}
function Empty({t}:{t:string}){return <div className="rounded-xl border border-dashed p-8 text-center text-muted-foreground">{t}</div>}
function DocEditor({ar,customers,customerId,setCustomerId,lines,setLines,discount,setDiscount,tax,setTax,validUntil,setValidUntil,notes,setNotes,add,label}:{ar:boolean;customers:Customer[];customerId:string;setCustomerId:(x:string)=>void;lines:Line[];setLines:(x:Line[])=>void;discount:number;setDiscount:(x:number)=>void;tax:number;setTax:(x:number)=>void;validUntil:string;setValidUntil:(x:string)=>void;notes:string;setNotes:(x:string)=>void;add:()=>void;label:string}){const preview=calc(lines,discount,tax);return <><div className="grid gap-2 md:grid-cols-3"><select value={customerId} onChange={e=>setCustomerId(e.target.value)} className="h-10 rounded-md border px-3"><option value="">{ar?"اختر العميل":"Select customer"}</option>{customers.map(x=><option key={x.id} value={x.id}>{x.name}{x.company?" — "+x.company:""}</option>)}</select><Button variant="outline" onClick={()=>setLines([...lines,{id:uid("L"),description:"",qty:1,unitPrice:0}])}><Plus/>{ar?"إضافة بند":"Add line"}</Button><Button onClick={add}><FileText/>{label}</Button></div><div className="mt-4 space-y-2">{lines.map((l,i)=><div key={l.id} className="grid grid-cols-[1fr_80px_120px_36px] gap-2"><input value={l.description} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,description:e.target.value}:x))} placeholder={ar?"المنتج/الخدمة":"Product/service"} className="h-10 rounded-md border px-3"/><input type="number" min="1" value={l.qty} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,qty:Math.max(1,Number(e.target.value))}:x))} className="h-10 rounded-md border px-2"/><input type="number" min="0" value={l.unitPrice} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,unitPrice:Math.max(0,Number(e.target.value))}:x))} className="h-10 rounded-md border px-2"/><button type="button" onClick={()=>setLines(lines.filter(x=>x.id!==l.id))} className="rounded-md border text-destructive"><Trash2 className="mx-auto h-4 w-4"/></button></div>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-4"><input type="number" min="0" value={discount} onChange={e=>setDiscount(Number(e.target.value)||0)} placeholder={ar?"الخصم":"Discount"} className="h-10 rounded-md border px-3"/><input type="number" min="0" value={tax} onChange={e=>setTax(Number(e.target.value)||0)} placeholder={ar?"الضريبة %":"Tax %"} className="h-10 rounded-md border px-3"/>{validUntil!==undefined&&<input type="date" value={validUntil} onChange={e=>setValidUntil(e.target.value)} className="h-10 rounded-md border px-3"/>}<div className="flex items-center rounded-md border bg-secondary px-3 text-sm font-bold">{ar?"الإجمالي":"Total"}: {money(preview.total)}</div></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder={ar?"ملاحظات":"Notes"} className="mt-2 min-h-20 w-full rounded-md border px-3 py-2"/></>}
function Doc({id,customer,amount,status,ar,onStatus,print,convert,canConvert}:{id:string;customer:string;amount:number;status:string;ar:boolean;onStatus:(x:string)=>void;print:()=>void;convert?:()=>void;canConvert?:boolean}){return <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-background p-4"><div><b>{id}</b><p className="text-sm">{customer} · {money(amount)}</p></div><div className="flex flex-wrap gap-2"><select value={status} onChange={e=>onStatus(e.target.value)} className="h-9 rounded-md border px-2 text-sm"><option value="draft">{ar?"مسودة":"Draft"}</option><option value="sent">{ar?"مرسل":"Sent"}</option><option value="accepted">{ar?"مقبول":"Accepted"}</option><option value="rejected">{ar?"مرفوض":"Rejected"}</option><option value="expired">{ar?"منتهي":"Expired"}</option></select><Button variant="outline" onClick={print}><FileDown/></Button>{canConvert&&convert&&<Button variant="outline" onClick={convert}>{ar?"تحويل لفاتورة":"Convert to invoice"}</Button>}</div></div>}
