import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { BadgeDollarSign, Building2, Calculator, FileText, Plus, Receipt, Search, Trash2, Truck, Users, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/components/language-provider";
import { PageIntro } from "@/components/site-sections";

type Customer={id:string;name:string;company:string;phone:string;email:string;address:string;createdAt:string};
type Supplier={id:string;name:string;company:string;phone:string;email:string;createdAt:string};
type Line={id:string;description:string;qty:number;unitPrice:number};
type Quote={id:string;customerId:string;status:"draft"|"sent"|"accepted"|"rejected";lines:Line[];discount:number;tax:number;createdAt:string};
type Invoice={id:string;customerId:string;status:"unpaid"|"partial"|"paid"|"overdue";lines:Line[];discount:number;tax:number;paid:number;createdAt:string};
type Cash={id:string;type:"income"|"expense";category:string;amount:number;currency:"EGP"|"USD";description:string;date:string};
type Tab="overview"|"customers"|"suppliers"|"quotes"|"invoices"|"cash"|"reports";
type Store={customers:Customer[];suppliers:Supplier[];quotes:Quote[];invoices:Invoice[];cash:Cash[]};

const KEY="az-business-data";
const EMPTY:Store={customers:[],suppliers:[],quotes:[],invoices:[],cash:[]};
const uid=(p:string)=>p+"-"+Date.now().toString(36).toUpperCase();
const total=(lines:Line[],discount=0,tax=0)=>{const subtotal=lines.reduce((s,x)=>s+x.qty*x.unitPrice,0);const net=Math.max(0,subtotal-discount);return net+net*tax/100};
const money=(n:number,c:"EGP"|"USD"="EGP")=>n.toLocaleString("en-US",{maximumFractionDigits:2})+" "+c;
const read=():Store=>{try{return {...EMPTY,...JSON.parse(localStorage.getItem(KEY)||"{}")};}catch{return EMPTY;}};

export const Route=createFileRoute("/business")({head:()=>({meta:[{title:"Business Center | AZ Solution BNS"},{name:"robots",content:"noindex,nofollow"}]}),component:BusinessPage});

function BusinessPage(){
 const {language}=useLanguage();const ar=language==="ar";const [data,setData]=useState<Store>(EMPTY);const [tab,setTab]=useState<Tab>("overview");const [search,setSearch]=useState("");
 const [customer,setCustomer]=useState({name:"",company:"",phone:"",email:"",address:""});const [supplier,setSupplier]=useState({name:"",company:"",phone:"",email:""});
 const [customerId,setCustomerId]=useState("");const [lines,setLines]=useState<Line[]>([{id:"1",description:"",qty:1,unitPrice:0}]);
 const [cash,setCash]=useState({type:"income" as Cash["type"],category:"Sale",amount:"",currency:"EGP" as Cash["currency"],description:""});
 useEffect(()=>setData(read()),[]);
 const save=(next:Store)=>{setData(next);localStorage.setItem(KEY,JSON.stringify(next));};
 const addCustomer=()=>{if(!customer.name||!customer.phone)return;save({...data,customers:[{id:uid("CUS"),...customer,createdAt:new Date().toISOString()},...data.customers]});setCustomer({name:"",company:"",phone:"",email:"",address:""});};
 const addSupplier=()=>{if(!supplier.name)return;save({...data,suppliers:[{id:uid("SUP"),...supplier,createdAt:new Date().toISOString()},...data.suppliers]});setSupplier({name:"",company:"",phone:"",email:""});};
 const createQuote=()=>{const ls=lines.filter(x=>x.description);if(!customerId||!ls.length)return;save({...data,quotes:[{id:uid("QT"),customerId,status:"draft",lines:ls,discount:0,tax:0,createdAt:new Date().toISOString()},...data.quotes]});setLines([{id:"1",description:"",qty:1,unitPrice:0}]);};
 const createInvoice=()=>{const ls=lines.filter(x=>x.description);if(!customerId||!ls.length)return;save({...data,invoices:[{id:uid("INV"),customerId,status:"unpaid",lines:ls,discount:0,tax:0,paid:0,createdAt:new Date().toISOString()},...data.invoices]});setLines([{id:"1",description:"",qty:1,unitPrice:0}]);};
 const addCash=()=>{const n=Number(cash.amount);if(!n)return;save({...data,cash:[{id:uid("TXN"),...cash,amount:n,date:new Date().toISOString()},...data.cash]});setCash({type:"income",category:"Sale",amount:"",currency:"EGP",description:""});};
 const name=(id:string)=>data.customers.find(x=>x.id===id)?.name||"—";
 const stats=useMemo(()=>{const income=data.cash.filter(x=>x.type==="income"&&x.currency==="EGP").reduce((s,x)=>s+x.amount,0);const expense=data.cash.filter(x=>x.type==="expense"&&x.currency==="EGP").reduce((s,x)=>s+x.amount,0);const outstanding=data.invoices.reduce((s,x)=>s+Math.max(0,total(x.lines,x.discount,x.tax)-x.paid),0);return{income,expense,profit:income-expense,outstanding,quoted:data.quotes.reduce((s,x)=>s+total(x.lines,x.discount,x.tax),0),invoiced:data.invoices.reduce((s,x)=>s+total(x.lines,x.discount,x.tax),0)}},[data]);
 const filtered=data.customers.filter(x=>(x.name+" "+x.company+" "+x.phone+" "+x.email).toLowerCase().includes(search.toLowerCase()));
 const updateQuote=(id:string,status:Quote["status"])=>save({...data,quotes:data.quotes.map(x=>x.id===id?{...x,status}:x)});
 const updateInvoice=(id:string,status:Invoice["status"],paid:number)=>save({...data,invoices:data.invoices.map(x=>x.id===id?{...x,status,paid}:x)});
 const tabs:[Tab,string,string,any][]=[["overview","نظرة عامة","Overview",BadgeDollarSign],["customers","العملاء","Customers",Users],["suppliers","الموردون","Suppliers",Truck],["quotes","عروض الأسعار","Quotations",FileText],["invoices","الفواتير","Invoices",Receipt],["cash","الحسابات","Cashflow",WalletCards],["reports","التقارير","Reports",Calculator]];
 return <><PageIntro icon={Building2} eyebrow={{ar:"نظام تشغيل الشركة",en:"Company Operating System"}} title={{ar:"AZ Solution Business OS",en:"AZ Solution Business OS"}} description={{ar:"CRM ومبيعات وعروض أسعار وفواتير وموردون وحسابات وتقارير في مركز واحد. البيانات حاليًا محلية لحين ربط قاعدة البيانات.",en:"CRM, sales, quotations, invoices, suppliers, cashflow and reporting in one center. Data is local until a database is connected."}}/><section className="bg-secondary py-8"><div className="container-shell"><div className="flex flex-wrap gap-2">{tabs.map(([id,a,e,I])=><button key={id} onClick={()=>setTab(id)} className={"inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm font-semibold "+(tab===id?"bg-primary text-primary-foreground":"bg-card hover:bg-accent")}><I className="h-4 w-4"/>{ar?a:e}</button>)}</div>
 {tab==="overview"&&<div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric t={ar?"الإيرادات":"Revenue"} v={money(stats.income)}/><Metric t={ar?"المصروفات":"Expenses"} v={money(stats.expense)}/><Metric t={ar?"صافي التشغيل":"Operating profit"} v={money(stats.profit)}/><Metric t={ar?"المستحق":"Outstanding"} v={money(stats.outstanding)}/><Metric t={ar?"قيمة العروض":"Quoted pipeline"} v={money(stats.quoted)}/><Metric t={ar?"الفواتير":"Invoiced"} v={money(stats.invoiced)}/><Metric t={ar?"العملاء":"Customers"} v={String(data.customers.length)}/><Metric t={ar?"الموردون":"Suppliers"} v={String(data.suppliers.length)}/></div>}
 {tab==="customers"&&<Panel t={ar?"العملاء والشركات":"Customers & Companies"}><div className="grid gap-2 md:grid-cols-5">{(["name","company","phone","email","address"] as const).map(k=><input key={k} value={customer[k]} onChange={e=>setCustomer({...customer,[k]:e.target.value})} placeholder={k==="name"?(ar?"اسم العميل":"Customer name"):k==="company"?(ar?"الشركة":"Company"):k} className="h-10 rounded-md border border-input bg-background px-3 text-sm"/>)}<Button onClick={addCustomer}><Plus/> {ar?"إضافة":"Add"}</Button></div><div className="mt-4 flex gap-2"><Search className="mt-3 h-4 w-4"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={ar?"بحث...":"Search..."} className="h-10 flex-1 rounded-md border px-3"/></div><div className="mt-4 grid gap-2">{filtered.map(x=><div key={x.id} className="flex flex-wrap items-center justify-between rounded-xl border bg-background p-4"><div><b>{x.name}</b><p className="text-xs text-muted-foreground">{x.company||"—"} · {x.phone} · {x.email||"—"}</p></div><Button variant="outline" onClick={()=>{setCustomerId(x.id);setTab("quotes")}}><FileText/>{ar?"عرض سعر":"Quote"}</Button></div>)}{!filtered.length&&<Empty t={ar?"لا يوجد عملاء":"No customers yet."}/>}</div></Panel>}
 {tab==="suppliers"&&<Panel t={ar?"الموردون":"Suppliers"}><div className="grid gap-2 md:grid-cols-5">{(["name","company","phone","email"] as const).map(k=><input key={k} value={supplier[k]} onChange={e=>setSupplier({...supplier,[k]:e.target.value})} placeholder={k} className="h-10 rounded-md border border-input bg-background px-3 text-sm"/>)}<Button onClick={addSupplier}><Plus/>{ar?"إضافة":"Add"}</Button></div><div className="mt-4 grid gap-2">{data.suppliers.map(x=><div key={x.id} className="rounded-xl border bg-background p-4"><b>{x.name}</b><p className="text-xs text-muted-foreground">{x.company||"—"} · {x.phone||"—"} · {x.email||"—"}</p></div>)}</div></Panel>}
 {tab==="quotes"&&<Panel t={ar?"عروض الأسعار":"Quotations"}><DocEditor ar={ar} customers={data.customers} customerId={customerId} setCustomerId={setCustomerId} lines={lines} setLines={setLines} add={createQuote} label={ar?"حفظ عرض السعر":"Save quotation"}/><div className="mt-6 space-y-2">{data.quotes.map(x=><Doc key={x.id} id={x.id} customer={name(x.customerId)} amount={total(x.lines)} status={x.status} ar={ar} onStatus={(s)=>updateQuote(x.id,s as Quote["status"])}/>)}</div></Panel>}
 {tab==="invoices"&&<Panel t={ar?"الفواتير والتحصيل":"Invoices & Collections"}><DocEditor ar={ar} customers={data.customers} customerId={customerId} setCustomerId={setCustomerId} lines={lines} setLines={setLines} add={createInvoice} label={ar?"إنشاء فاتورة":"Create invoice"}/><div className="mt-6 space-y-2">{data.invoices.map(x=><div key={x.id} className="rounded-xl border bg-background p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><b>{x.id}</b><p className="text-sm">{name(x.customerId)} · {money(total(x.lines))}</p></div><div className="flex gap-2"><select value={x.status} onChange={e=>updateInvoice(x.id,e.target.value as Invoice["status"],x.paid)} className="h-9 rounded-md border px-2 text-sm"><option value="unpaid">{ar?"غير مدفوع":"Unpaid"}</option><option value="partial">{ar?"جزئي":"Partial"}</option><option value="paid">{ar?"مدفوع":"Paid"}</option><option value="overdue">{ar?"متأخر":"Overdue"}</option></select><input type="number" value={x.paid} onChange={e=>updateInvoice(x.id,x.status,Number(e.target.value))} className="h-9 w-28 rounded-md border px-2 text-sm" placeholder="Paid"/></div></div></div>)}</div></Panel>}
 {tab==="cash"&&<Panel t={ar?"الإيرادات والمصروفات":"Income & Expenses"}><div className="grid gap-2 md:grid-cols-5"><select value={cash.type} onChange={e=>setCash({...cash,type:e.target.value as Cash["type"]})} className="h-10 rounded-md border px-3"><option value="income">{ar?"إيراد":"Income"}</option><option value="expense">{ar?"مصروف":"Expense"}</option></select><input value={cash.category} onChange={e=>setCash({...cash,category:e.target.value})} className="h-10 rounded-md border px-3"/><input type="number" value={cash.amount} onChange={e=>setCash({...cash,amount:e.target.value})} placeholder="Amount" className="h-10 rounded-md border px-3"/><select value={cash.currency} onChange={e=>setCash({...cash,currency:e.target.value as Cash["currency"]})} className="h-10 rounded-md border px-3"><option>EGP</option><option>USD</option></select><Button onClick={addCash}><Plus/>{ar?"تسجيل":"Record"}</Button></div><input value={cash.description} onChange={e=>setCash({...cash,description:e.target.value})} placeholder={ar?"وصف العملية":"Description"} className="mt-2 h-10 w-full rounded-md border px-3"/><div className="mt-4 space-y-2">{data.cash.map(x=><div key={x.id} className="flex justify-between rounded-xl border bg-background p-4"><span><b>{x.category}</b><p className="text-xs text-muted-foreground">{x.description}</p></span><b className={x.type==="expense"?"text-destructive":""}>{x.type==="expense"?"-":"+"}{money(x.amount,x.currency)}</b></div>)}</div></Panel>}
 {tab==="reports"&&<Panel t={ar?"التقارير":"Reports"}><div className="grid gap-4 md:grid-cols-2"><Metric t={ar?"الإيرادات":"Revenue"} v={money(stats.income)}/><Metric t={ar?"المصروفات":"Expenses"} v={money(stats.expense)}/><Metric t={ar?"صافي التشغيل":"Operating profit"} v={money(stats.profit)}/><Metric t={ar?"هامش التشغيل":"Operating margin"} v={stats.income?String(((stats.profit/stats.income)*100).toFixed(1))+"%":"0%"}/></div><p className="mt-5 rounded-xl bg-secondary p-4 text-sm leading-7">{ar?"هذا نظام تشغيلي مبسط وليس نظام محاسبة قانوني. قبل الاعتماد الرسمي نحتاج قاعدة بيانات وصلاحيات وسجل تدقيق ومراجعة محاسب.":"This is an operational system, not statutory accounting software. Production use requires a database, permissions, audit trail and accounting review."}</p></Panel>}
 </div></section></>;
}
function Metric({t,v}:{t:string;v:string}){return <div className="stat-card"><p className="text-sm text-muted-foreground">{t}</p><p className="mt-2 text-2xl font-black">{v}</p></div>}
function Panel({t,children}:{t:string;children:ReactNode}){return <div className="mt-6 rounded-2xl border border-border bg-card p-5 shadow-sm"><h2 className="text-xl font-black">{t}</h2>{children}</div>}
function Empty({t}:{t:string}){return <div className="rounded-xl border border-dashed p-8 text-center text-muted-foreground">{t}</div>}
function DocEditor({ar,customers,customerId,setCustomerId,lines,setLines,add,label}:{ar:boolean;customers:Customer[];customerId:string;setCustomerId:(x:string)=>void;lines:Line[];setLines:(x:Line[])=>void;add:()=>void;label:string}){return <><div className="grid gap-2 md:grid-cols-3"><select value={customerId} onChange={e=>setCustomerId(e.target.value)} className="h-10 rounded-md border px-3"><option value="">{ar?"اختر العميل":"Select customer"}</option>{customers.map(x=><option key={x.id} value={x.id}>{x.name}{x.company?" — "+x.company:""}</option>)}</select><Button variant="outline" onClick={()=>setLines([...lines,{id:uid("L"),description:"",qty:1,unitPrice:0}])}><Plus/>{ar?"إضافة بند":"Add line"}</Button><Button onClick={add}><FileText/>{label}</Button></div><div className="mt-4 space-y-2">{lines.map((l,i)=><div key={l.id} className="grid grid-cols-[1fr_90px_120px_36px] gap-2"><input value={l.description} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,description:e.target.value}:x))} placeholder={ar?"المنتج/الخدمة":"Product/service"} className="h-10 rounded-md border px-3"/><input type="number" value={l.qty} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,qty:Number(e.target.value)}:x))} className="h-10 rounded-md border px-2"/><input type="number" value={l.unitPrice} onChange={e=>setLines(lines.map((x,j)=>j===i?{...x,unitPrice:Number(e.target.value)}:x))} className="h-10 rounded-md border px-2"/><button onClick={()=>setLines(lines.filter(x=>x.id!==l.id))} className="rounded-md border text-destructive"><Trash2 className="mx-auto h-4 w-4"/></button></div>)}</div></>}
function Doc({id,customer,amount,status,ar,onStatus}:{id:string;customer:string;amount:number;status:string;ar:boolean;onStatus:(x:string)=>void}){return <div className="flex flex-wrap items-center justify-between rounded-xl border bg-background p-4"><div><b>{id}</b><p className="text-sm">{customer} · {money(amount)}</p></div><select value={status} onChange={e=>onStatus(e.target.value)} className="h-9 rounded-md border px-2 text-sm"><option value="draft">{ar?"مسودة":"Draft"}</option><option value="sent">{ar?"مرسل":"Sent"}</option><option value="accepted">{ar?"مقبول":"Accepted"}</option><option value="rejected">{ar?"مرفوض":"Rejected"}</option></select></div>}
