import { createFileRoute, Link } from "@tanstack/react-router";
import { MapPin, MessageSquareText, Phone, ArrowUpRight, Clock3 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageIntro } from "@/components/site-sections";
import { useLanguage } from "@/components/language-provider";
import { SITE_CONFIG } from "@/lib/site-data";

export const Route = createFileRoute("/contact")({ head: () => ({ meta: [
  { title: "Contact AZ Solution BNS" }, { name: "description", content: "Contact AZ Solution for IT solutions, supplies, maintenance and field support across Beni Suef and Upper Egypt." }, { property: "og:title", content: "Contact AZ Solution BNS" }, { property: "og:description", content: "Discuss your infrastructure, network, security, supply or support requirements." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/contact" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/contact" }] }), component: ContactPage });
function ContactPage() { const { language, t } = useLanguage(); const whatsapp=SITE_CONFIG.whatsappUrl; const hasWhatsapp=whatsapp.startsWith("https://wa.me/"); const items = [{ icon: Phone, title: language === "ar" ? "الهاتف / واتساب" : "Phone / WhatsApp", value: SITE_CONFIG.phone }, { icon: MapPin, title: language === "ar" ? "منطقة الخدمة" : "Service area", value: t(SITE_CONFIG.serviceArea) }, { icon: Clock3, title: language === "ar" ? "مواعيد العمل" : "Business hours", value: t(SITE_CONFIG.businessHours) }]; return <><PageIntro icon={MessageSquareText} eyebrow={{ ar: "تواصل معنا", en: "Contact" }} title={{ ar: "لنبدأ من متطلباتك", en: "Let’s begin with your requirements" }} description={{ ar: "شاركنا نطاق العمل المطلوب وسنساعدك في تنظيم الخطوة التالية. يمكنك التواصل معنا مباشرة عبر الهاتف أو واتساب.", en: "Share the required scope and we will help organize the next step. You can contact us directly by phone or WhatsApp." }} /><section className="py-20 md:py-28"><div className="container-shell grid gap-8 lg:grid-cols-[1fr_0.8fr]"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-1">{items.map(({ icon: Icon, title, value }) => <div key={title} className="content-card flex items-center gap-5 p-6"><span className="grid size-12 shrink-0 place-items-center rounded-md bg-tech-soft text-tech"><Icon /></span><div><h2 className="text-sm font-bold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{value}</p></div></div>)}</div><div className="contact-cta rounded-3xl bg-ink p-8 text-ink-foreground shadow-elevated md:p-10"><p className="eyebrow text-tech-bright">AZ Solution BNS</p><h2 className="mt-4 text-3xl font-bold">{language === "ar" ? "هل لديك مشروع محدد؟" : "Have a defined project?"}</h2><p className="mt-4 text-sm leading-7 text-ink-muted">{language === "ar" ? "نموذج عرض السعر يجمع تفاصيل المشروع والخدمة والملفات المساندة في طلب واحد منظم." : "The quote form gathers your project, service, and supporting file details into one structured request."}</p><Button asChild className="mt-7" size="lg"><Link to="/quote">{language === "ar" ? "افتح نموذج الطلب" : "Open quote form"}</Link></Button><div className="mt-8 grid gap-3 sm:grid-cols-2"><Button asChild size="lg"><Link to="/quote">{language === "ar" ? "طلب عرض سعر" : "Request a quote"}<ArrowUpRight /></Link></Button>{hasWhatsapp ? <Button asChild variant="outline" size="lg"><a href={whatsapp} target="_blank" rel="noreferrer">{language === "ar" ? "ابدأ محادثة واتساب" : "Start WhatsApp chat"}<ArrowUpRight /></a></Button> : <Button variant="outline" size="lg" disabled>{language === "ar" ? "واتساب — أضف الرقم أولاً" : "WhatsApp — add number first"}</Button>}</div></div></div></section></> }